name: CI Integration

on:
  push:
    branches:
      - develop
      - 'feature/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Dar permissão ao Maven Wrapper
        run: chmod +x mvnw

      - name: Rodar testes unitários
        run: ./mvnw test